/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package app.namsor.client.models

import app.namsor.client.models.PersonalNameGenderedOut

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param personalNames Classified genderized names
 */


data class BatchPersonalNameGenderedOut (

    /* Classified genderized names */
    @Json(name = "personalNames")
    val personalNames: kotlin.collections.List<PersonalNameGenderedOut>? = null

) {


}

