/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package app.namsor.client.models

import app.namsor.client.models.NameMatchCandidatesOut

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param namesAndMatchCandidates Classified matched names
 */


data class BatchNameMatchCandidatesOut (

    /* Classified matched names */
    @Json(name = "namesAndMatchCandidates")
    val namesAndMatchCandidates: kotlin.collections.List<NameMatchCandidatesOut>? = null

) {


}

