/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package app.namsor.client.models

import app.namsor.client.models.PersonalNameGeoOut

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param personalNames Classified geo names
 */


data class BatchPersonalNameGeoOut (

    /* Classified geo names */
    @Json(name = "personalNames")
    val personalNames: kotlin.collections.List<PersonalNameGeoOut>? = null

) {


}

