/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package app.namsor.client.models

import app.namsor.client.models.CommunityEngageOut

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param engagementCandidates Classified community engagement candidates
 */


data class BatchCommunityEngageOut (

    /* Classified community engagement candidates */
    @Json(name = "engagementCandidates")
    val engagementCandidates: kotlin.collections.List<CommunityEngageOut>? = null

) {


}

