/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package app.namsor.client.models

import app.namsor.client.models.FirstLastNameIn
import app.namsor.client.models.PersonalNameIn

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param name1 
 * @param name2 
 */


data class MatchPersonalFirstLastNameIn (

    @Json(name = "id")
    val id: kotlin.String? = null,

    @Json(name = "name1")
    val name1: FirstLastNameIn? = null,

    @Json(name = "name2")
    val name2: PersonalNameIn? = null

) {


}

