/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package app.namsor.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * The software version.
 *
 * @param softwareNameAndVersion The software version
 * @param softwareVersion The software version major minor build
 */


data class SoftwareVersionOut (

    /* The software version */
    @Json(name = "softwareNameAndVersion")
    val softwareNameAndVersion: kotlin.String? = null,

    /* The software version major minor build */
    @Json(name = "softwareVersion")
    val softwareVersion: kotlin.collections.List<kotlin.Int>? = null

) {


}

