<?php
/**
 * FirstLastNamePhoneCodedOut
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Namsor\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * NamSor API v2
 *
 * NamSor API v2 : enpoints to process personal names (gender, cultural origin or ethnicity) in all alphabets or languages. By default, enpoints use 1 unit per name (ex. Gender), but Ethnicity classification uses 10 to 20 units per name depending on taxonomy. Use GET methods for small tests, but prefer POST methods for higher throughput (batch processing of up to 100 names at a time). Need something you can't find here? We have many more features coming soon. Let us know, we'll do our best to add it!
 *
 * The version of the OpenAPI document: 2.0.29
 * Contact: contact@namsor.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.11.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Namsor\Client\Model;

use \ArrayAccess;
use \Namsor\Client\ObjectSerializer;

/**
 * FirstLastNamePhoneCodedOut Class Doc Comment
 *
 * @category Class
 * @description Represents the output of inferring the LIKELY country and phone code from a personal name and phone number.
 * @package  Namsor\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class FirstLastNamePhoneCodedOut implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'FirstLastNamePhoneCodedOut';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'script' => 'string',
        'id' => 'string',
        'explanation' => 'string',
        'first_name' => 'string',
        'last_name' => 'string',
        'international_phone_number_verified' => 'string',
        'phone_country_iso2_verified' => 'string',
        'phone_country_code' => 'int',
        'phone_country_code_alt' => 'int',
        'phone_country_iso2' => 'string',
        'phone_country_iso2_alt' => 'string',
        'origin_country_iso2' => 'string',
        'origin_country_iso2_alt' => 'string',
        'phone_number' => 'string',
        'verified' => 'bool',
        'score' => 'float',
        'country_iso2' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'script' => null,
        'id' => null,
        'explanation' => null,
        'first_name' => null,
        'last_name' => null,
        'international_phone_number_verified' => null,
        'phone_country_iso2_verified' => null,
        'phone_country_code' => 'int32',
        'phone_country_code_alt' => 'int32',
        'phone_country_iso2' => null,
        'phone_country_iso2_alt' => null,
        'origin_country_iso2' => null,
        'origin_country_iso2_alt' => null,
        'phone_number' => null,
        'verified' => null,
        'score' => 'double',
        'country_iso2' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'script' => false,
        'id' => false,
        'explanation' => false,
        'first_name' => false,
        'last_name' => false,
        'international_phone_number_verified' => false,
        'phone_country_iso2_verified' => false,
        'phone_country_code' => false,
        'phone_country_code_alt' => false,
        'phone_country_iso2' => false,
        'phone_country_iso2_alt' => false,
        'origin_country_iso2' => false,
        'origin_country_iso2_alt' => false,
        'phone_number' => false,
        'verified' => false,
        'score' => false,
        'country_iso2' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'script' => 'script',
        'id' => 'id',
        'explanation' => 'explanation',
        'first_name' => 'firstName',
        'last_name' => 'lastName',
        'international_phone_number_verified' => 'internationalPhoneNumberVerified',
        'phone_country_iso2_verified' => 'phoneCountryIso2Verified',
        'phone_country_code' => 'phoneCountryCode',
        'phone_country_code_alt' => 'phoneCountryCodeAlt',
        'phone_country_iso2' => 'phoneCountryIso2',
        'phone_country_iso2_alt' => 'phoneCountryIso2Alt',
        'origin_country_iso2' => 'originCountryIso2',
        'origin_country_iso2_alt' => 'originCountryIso2Alt',
        'phone_number' => 'phoneNumber',
        'verified' => 'verified',
        'score' => 'score',
        'country_iso2' => 'countryIso2'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'script' => 'setScript',
        'id' => 'setId',
        'explanation' => 'setExplanation',
        'first_name' => 'setFirstName',
        'last_name' => 'setLastName',
        'international_phone_number_verified' => 'setInternationalPhoneNumberVerified',
        'phone_country_iso2_verified' => 'setPhoneCountryIso2Verified',
        'phone_country_code' => 'setPhoneCountryCode',
        'phone_country_code_alt' => 'setPhoneCountryCodeAlt',
        'phone_country_iso2' => 'setPhoneCountryIso2',
        'phone_country_iso2_alt' => 'setPhoneCountryIso2Alt',
        'origin_country_iso2' => 'setOriginCountryIso2',
        'origin_country_iso2_alt' => 'setOriginCountryIso2Alt',
        'phone_number' => 'setPhoneNumber',
        'verified' => 'setVerified',
        'score' => 'setScore',
        'country_iso2' => 'setCountryIso2'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'script' => 'getScript',
        'id' => 'getId',
        'explanation' => 'getExplanation',
        'first_name' => 'getFirstName',
        'last_name' => 'getLastName',
        'international_phone_number_verified' => 'getInternationalPhoneNumberVerified',
        'phone_country_iso2_verified' => 'getPhoneCountryIso2Verified',
        'phone_country_code' => 'getPhoneCountryCode',
        'phone_country_code_alt' => 'getPhoneCountryCodeAlt',
        'phone_country_iso2' => 'getPhoneCountryIso2',
        'phone_country_iso2_alt' => 'getPhoneCountryIso2Alt',
        'origin_country_iso2' => 'getOriginCountryIso2',
        'origin_country_iso2_alt' => 'getOriginCountryIso2Alt',
        'phone_number' => 'getPhoneNumber',
        'verified' => 'getVerified',
        'score' => 'getScore',
        'country_iso2' => 'getCountryIso2'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('script', $data ?? [], null);
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('explanation', $data ?? [], null);
        $this->setIfExists('first_name', $data ?? [], null);
        $this->setIfExists('last_name', $data ?? [], null);
        $this->setIfExists('international_phone_number_verified', $data ?? [], null);
        $this->setIfExists('phone_country_iso2_verified', $data ?? [], null);
        $this->setIfExists('phone_country_code', $data ?? [], null);
        $this->setIfExists('phone_country_code_alt', $data ?? [], null);
        $this->setIfExists('phone_country_iso2', $data ?? [], null);
        $this->setIfExists('phone_country_iso2_alt', $data ?? [], null);
        $this->setIfExists('origin_country_iso2', $data ?? [], null);
        $this->setIfExists('origin_country_iso2_alt', $data ?? [], null);
        $this->setIfExists('phone_number', $data ?? [], null);
        $this->setIfExists('verified', $data ?? [], null);
        $this->setIfExists('score', $data ?? [], null);
        $this->setIfExists('country_iso2', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['score']) && ($this->container['score'] > 100)) {
            $invalidProperties[] = "invalid value for 'score', must be smaller than or equal to 100.";
        }

        if (!is_null($this->container['score']) && ($this->container['score'] < 0)) {
            $invalidProperties[] = "invalid value for 'score', must be bigger than or equal to 0.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets script
     *
     * @return string|null
     */
    public function getScript()
    {
        return $this->container['script'];
    }

    /**
     * Sets script
     *
     * @param string|null $script script
     *
     * @return self
     */
    public function setScript($script)
    {
        if (is_null($script)) {
            throw new \InvalidArgumentException('non-nullable script cannot be null');
        }
        $this->container['script'] = $script;

        return $this;
    }

    /**
     * Gets id
     *
     * @return string|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string|null $id id
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets explanation
     *
     * @return string|null
     */
    public function getExplanation()
    {
        return $this->container['explanation'];
    }

    /**
     * Sets explanation
     *
     * @param string|null $explanation explanation
     *
     * @return self
     */
    public function setExplanation($explanation)
    {
        if (is_null($explanation)) {
            throw new \InvalidArgumentException('non-nullable explanation cannot be null');
        }
        $this->container['explanation'] = $explanation;

        return $this;
    }

    /**
     * Gets first_name
     *
     * @return string|null
     */
    public function getFirstName()
    {
        return $this->container['first_name'];
    }

    /**
     * Sets first_name
     *
     * @param string|null $first_name The first name (also known as given name)
     *
     * @return self
     */
    public function setFirstName($first_name)
    {
        if (is_null($first_name)) {
            throw new \InvalidArgumentException('non-nullable first_name cannot be null');
        }
        $this->container['first_name'] = $first_name;

        return $this;
    }

    /**
     * Gets last_name
     *
     * @return string|null
     */
    public function getLastName()
    {
        return $this->container['last_name'];
    }

    /**
     * Sets last_name
     *
     * @param string|null $last_name The last name (also known as family name, or surname)
     *
     * @return self
     */
    public function setLastName($last_name)
    {
        if (is_null($last_name)) {
            throw new \InvalidArgumentException('non-nullable last_name cannot be null');
        }
        $this->container['last_name'] = $last_name;

        return $this;
    }

    /**
     * Gets international_phone_number_verified
     *
     * @return string|null
     */
    public function getInternationalPhoneNumberVerified()
    {
        return $this->container['international_phone_number_verified'];
    }

    /**
     * Sets international_phone_number_verified
     *
     * @param string|null $international_phone_number_verified The normalized phone number, verified using libphonenumber.
     *
     * @return self
     */
    public function setInternationalPhoneNumberVerified($international_phone_number_verified)
    {
        if (is_null($international_phone_number_verified)) {
            throw new \InvalidArgumentException('non-nullable international_phone_number_verified cannot be null');
        }
        $this->container['international_phone_number_verified'] = $international_phone_number_verified;

        return $this;
    }

    /**
     * Gets phone_country_iso2_verified
     *
     * @return string|null
     */
    public function getPhoneCountryIso2Verified()
    {
        return $this->container['phone_country_iso2_verified'];
    }

    /**
     * Sets phone_country_iso2_verified
     *
     * @param string|null $phone_country_iso2_verified The phone ISO2 country code, verified using libphonenumber.
     *
     * @return self
     */
    public function setPhoneCountryIso2Verified($phone_country_iso2_verified)
    {
        if (is_null($phone_country_iso2_verified)) {
            throw new \InvalidArgumentException('non-nullable phone_country_iso2_verified cannot be null');
        }
        $this->container['phone_country_iso2_verified'] = $phone_country_iso2_verified;

        return $this;
    }

    /**
     * Gets phone_country_code
     *
     * @return int|null
     */
    public function getPhoneCountryCode()
    {
        return $this->container['phone_country_code'];
    }

    /**
     * Sets phone_country_code
     *
     * @param int|null $phone_country_code The phone country code of the phone number, verified using libphonenumber.
     *
     * @return self
     */
    public function setPhoneCountryCode($phone_country_code)
    {
        if (is_null($phone_country_code)) {
            throw new \InvalidArgumentException('non-nullable phone_country_code cannot be null');
        }
        $this->container['phone_country_code'] = $phone_country_code;

        return $this;
    }

    /**
     * Gets phone_country_code_alt
     *
     * @return int|null
     */
    public function getPhoneCountryCodeAlt()
    {
        return $this->container['phone_country_code_alt'];
    }

    /**
     * Sets phone_country_code_alt
     *
     * @param int|null $phone_country_code_alt The best alternative phone country code of the phone number.
     *
     * @return self
     */
    public function setPhoneCountryCodeAlt($phone_country_code_alt)
    {
        if (is_null($phone_country_code_alt)) {
            throw new \InvalidArgumentException('non-nullable phone_country_code_alt cannot be null');
        }
        $this->container['phone_country_code_alt'] = $phone_country_code_alt;

        return $this;
    }

    /**
     * Gets phone_country_iso2
     *
     * @return string|null
     */
    public function getPhoneCountryIso2()
    {
        return $this->container['phone_country_iso2'];
    }

    /**
     * Sets phone_country_iso2
     *
     * @param string|null $phone_country_iso2 The likely country of the phone number.
     *
     * @return self
     */
    public function setPhoneCountryIso2($phone_country_iso2)
    {
        if (is_null($phone_country_iso2)) {
            throw new \InvalidArgumentException('non-nullable phone_country_iso2 cannot be null');
        }
        $this->container['phone_country_iso2'] = $phone_country_iso2;

        return $this;
    }

    /**
     * Gets phone_country_iso2_alt
     *
     * @return string|null
     */
    public function getPhoneCountryIso2Alt()
    {
        return $this->container['phone_country_iso2_alt'];
    }

    /**
     * Sets phone_country_iso2_alt
     *
     * @param string|null $phone_country_iso2_alt The best alternative country of the phone number.
     *
     * @return self
     */
    public function setPhoneCountryIso2Alt($phone_country_iso2_alt)
    {
        if (is_null($phone_country_iso2_alt)) {
            throw new \InvalidArgumentException('non-nullable phone_country_iso2_alt cannot be null');
        }
        $this->container['phone_country_iso2_alt'] = $phone_country_iso2_alt;

        return $this;
    }

    /**
     * Gets origin_country_iso2
     *
     * @return string|null
     */
    public function getOriginCountryIso2()
    {
        return $this->container['origin_country_iso2'];
    }

    /**
     * Sets origin_country_iso2
     *
     * @param string|null $origin_country_iso2 The likely country of origin of the name.
     *
     * @return self
     */
    public function setOriginCountryIso2($origin_country_iso2)
    {
        if (is_null($origin_country_iso2)) {
            throw new \InvalidArgumentException('non-nullable origin_country_iso2 cannot be null');
        }
        $this->container['origin_country_iso2'] = $origin_country_iso2;

        return $this;
    }

    /**
     * Gets origin_country_iso2_alt
     *
     * @return string|null
     */
    public function getOriginCountryIso2Alt()
    {
        return $this->container['origin_country_iso2_alt'];
    }

    /**
     * Sets origin_country_iso2_alt
     *
     * @param string|null $origin_country_iso2_alt The best alternative country of origin of the name.
     *
     * @return self
     */
    public function setOriginCountryIso2Alt($origin_country_iso2_alt)
    {
        if (is_null($origin_country_iso2_alt)) {
            throw new \InvalidArgumentException('non-nullable origin_country_iso2_alt cannot be null');
        }
        $this->container['origin_country_iso2_alt'] = $origin_country_iso2_alt;

        return $this;
    }

    /**
     * Gets phone_number
     *
     * @return string|null
     */
    public function getPhoneNumber()
    {
        return $this->container['phone_number'];
    }

    /**
     * Sets phone_number
     *
     * @param string|null $phone_number The input phone number.
     *
     * @return self
     */
    public function setPhoneNumber($phone_number)
    {
        if (is_null($phone_number)) {
            throw new \InvalidArgumentException('non-nullable phone_number cannot be null');
        }
        $this->container['phone_number'] = $phone_number;

        return $this;
    }

    /**
     * Gets verified
     *
     * @return bool|null
     */
    public function getVerified()
    {
        return $this->container['verified'];
    }

    /**
     * Sets verified
     *
     * @param bool|null $verified Indicates if the phone number could be positively verified using libphonenumber.
     *
     * @return self
     */
    public function setVerified($verified)
    {
        if (is_null($verified)) {
            throw new \InvalidArgumentException('non-nullable verified cannot be null');
        }
        $this->container['verified'] = $verified;

        return $this;
    }

    /**
     * Gets score
     *
     * @return float|null
     */
    public function getScore()
    {
        return $this->container['score'];
    }

    /**
     * Sets score
     *
     * @param float|null $score Higher score is better, but score is not normalized. Use calibratedProbability if available.
     *
     * @return self
     */
    public function setScore($score)
    {
        if (is_null($score)) {
            throw new \InvalidArgumentException('non-nullable score cannot be null');
        }

        if (($score > 100)) {
            throw new \InvalidArgumentException('invalid value for $score when calling FirstLastNamePhoneCodedOut., must be smaller than or equal to 100.');
        }
        if (($score < 0)) {
            throw new \InvalidArgumentException('invalid value for $score when calling FirstLastNamePhoneCodedOut., must be bigger than or equal to 0.');
        }

        $this->container['score'] = $score;

        return $this;
    }

    /**
     * Gets country_iso2
     *
     * @return string|null
     */
    public function getCountryIso2()
    {
        return $this->container['country_iso2'];
    }

    /**
     * Sets country_iso2
     *
     * @param string|null $country_iso2 country_iso2
     *
     * @return self
     */
    public function setCountryIso2($country_iso2)
    {
        if (is_null($country_iso2)) {
            throw new \InvalidArgumentException('non-nullable country_iso2 cannot be null');
        }
        $this->container['country_iso2'] = $country_iso2;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


