generatorName: php
additionalProperties:
  invokerPackage: "OpenAPI\\Client"
  packageName: openapi/client
  composerPackageName: openapi/client
  packageVersion: "1.0.0"
  artifactVersion: "1.0.0"
  oseg.composerPackageName: oseg/petstore_examples
  oseg.namespace: OSEG\PetStoreExamples
  oseg.autoloadLocation: "__DIR__ . '/../vendor/autoload.php'"
  oseg.ignoreOptionalUnset: false
  oseg.security.api_key.api_key: YOUR_API_KEY
  oseg.security.petstore_auth.access_token: YOUR_ACCESS_TOKEN
globalProperties:
  apiTests: false
  modelTests: false
  apiDocs: false
  modelDocs: false
