generatorName: python
additionalProperties:
  packageName: openapi_client
  projectName: openapi-client
  oseg.propertyNamingConvention: camel_case
  oseg.security.api_key.api_key: YOUR_API_KEY
  oseg.security.petstore_auth.access_token: YOUR_ACCESS_TOKEN
globalProperties:
  apiTests: false
  modelTests: false
  apiDocs: false
  modelDocs: false
