generatorName: typescript-node
additionalProperties:
  npmName: openapi_client
  oseg.npmName: "@oseg/petstore"
  oseg.security.api_key.api_key: YOUR_API_KEY
  oseg.security.petstore_auth.access_token: YOUR_ACCESS_TOKEN
  oseg.printApiCallProperty: true
globalProperties:
  apiTests: false
  modelTests: false
  apiDocs: false
  modelDocs: false
