/*
 * NamSor API v2
 *
 * NamSor API v2 : enpoints to process personal names (gender, cultural origin or ethnicity) in all alphabets or languages. By default, enpoints use 1 unit per name (ex. Gender), but Ethnicity classification uses 10 to 20 units per name depending on taxonomy. Use GET methods for small tests, but prefer POST methods for higher throughput (batch processing of up to 100 names at a time). Need something you can't find here? We have many more features coming soon. Let us know, we'll do our best to add it! 
 *
 * The version of the OpenAPI document: 2.0.29
 * Contact: contact@namsor.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = App.Namsor.Client.OpenAPIDateConverter;

namespace App.Namsor.Model
{
    /// <summary>
    /// Represents the output of inferring the LIKELY gender from a list of personal names.
    /// </summary>
    [DataContract(Name = "BatchFirstLastNameGenderedOut")]
    public partial class BatchFirstLastNameGenderedOut : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BatchFirstLastNameGenderedOut" /> class.
        /// </summary>
        /// <param name="personalNames">Classified genderized names.</param>
        public BatchFirstLastNameGenderedOut(List<FirstLastNameGenderedOut> personalNames = default(List<FirstLastNameGenderedOut>))
        {
            this.PersonalNames = personalNames;
        }

        /// <summary>
        /// Classified genderized names
        /// </summary>
        /// <value>Classified genderized names</value>
        [DataMember(Name = "personalNames", EmitDefaultValue = false)]
        public List<FirstLastNameGenderedOut> PersonalNames { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class BatchFirstLastNameGenderedOut {\n");
            sb.Append("  PersonalNames: ").Append(PersonalNames).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
