export * from './aIConfigsBetaApi';
import { AIConfigsBetaApi } from './aIConfigsBetaApi';
export * from './accessTokensApi';
import { AccessTokensApi } from './accessTokensApi';
export * from './accountMembersApi';
import { AccountMembersApi } from './accountMembersApi';
export * from './accountMembersBetaApi';
import { AccountMembersBetaApi } from './accountMembersBetaApi';
export * from './accountUsageBetaApi';
import { AccountUsageBetaApi } from './accountUsageBetaApi';
export * from './applicationsBetaApi';
import { ApplicationsBetaApi } from './applicationsBetaApi';
export * from './approvalsApi';
import { ApprovalsApi } from './approvalsApi';
export * from './approvalsBetaApi';
import { ApprovalsBetaApi } from './approvalsBetaApi';
export * from './auditLogApi';
import { AuditLogApi } from './auditLogApi';
export * from './codeReferencesApi';
import { CodeReferencesApi } from './codeReferencesApi';
export * from './contextSettingsApi';
import { ContextSettingsApi } from './contextSettingsApi';
export * from './contextsApi';
import { ContextsApi } from './contextsApi';
export * from './customRolesApi';
import { CustomRolesApi } from './customRolesApi';
export * from './dataExportDestinationsApi';
import { DataExportDestinationsApi } from './dataExportDestinationsApi';
export * from './environmentsApi';
import { EnvironmentsApi } from './environmentsApi';
export * from './experimentsApi';
import { ExperimentsApi } from './experimentsApi';
export * from './featureFlagsApi';
import { FeatureFlagsApi } from './featureFlagsApi';
export * from './featureFlagsBetaApi';
import { FeatureFlagsBetaApi } from './featureFlagsBetaApi';
export * from './flagImportConfigurationsBetaApi';
import { FlagImportConfigurationsBetaApi } from './flagImportConfigurationsBetaApi';
export * from './flagLinksBetaApi';
import { FlagLinksBetaApi } from './flagLinksBetaApi';
export * from './flagTriggersApi';
import { FlagTriggersApi } from './flagTriggersApi';
export * from './followFlagsApi';
import { FollowFlagsApi } from './followFlagsApi';
export * from './holdoutsBetaApi';
import { HoldoutsBetaApi } from './holdoutsBetaApi';
export * from './insightsChartsBetaApi';
import { InsightsChartsBetaApi } from './insightsChartsBetaApi';
export * from './insightsDeploymentsBetaApi';
import { InsightsDeploymentsBetaApi } from './insightsDeploymentsBetaApi';
export * from './insightsFlagEventsBetaApi';
import { InsightsFlagEventsBetaApi } from './insightsFlagEventsBetaApi';
export * from './insightsPullRequestsBetaApi';
import { InsightsPullRequestsBetaApi } from './insightsPullRequestsBetaApi';
export * from './insightsRepositoriesBetaApi';
import { InsightsRepositoriesBetaApi } from './insightsRepositoriesBetaApi';
export * from './insightsScoresBetaApi';
import { InsightsScoresBetaApi } from './insightsScoresBetaApi';
export * from './integrationAuditLogSubscriptionsApi';
import { IntegrationAuditLogSubscriptionsApi } from './integrationAuditLogSubscriptionsApi';
export * from './integrationDeliveryConfigurationsBetaApi';
import { IntegrationDeliveryConfigurationsBetaApi } from './integrationDeliveryConfigurationsBetaApi';
export * from './integrationsBetaApi';
import { IntegrationsBetaApi } from './integrationsBetaApi';
export * from './layersApi';
import { LayersApi } from './layersApi';
export * from './metricsApi';
import { MetricsApi } from './metricsApi';
export * from './metricsBetaApi';
import { MetricsBetaApi } from './metricsBetaApi';
export * from './oAuth2ClientsApi';
import { OAuth2ClientsApi } from './oAuth2ClientsApi';
export * from './otherApi';
import { OtherApi } from './otherApi';
export * from './persistentStoreIntegrationsBetaApi';
import { PersistentStoreIntegrationsBetaApi } from './persistentStoreIntegrationsBetaApi';
export * from './projectsApi';
import { ProjectsApi } from './projectsApi';
export * from './relayProxyConfigurationsApi';
import { RelayProxyConfigurationsApi } from './relayProxyConfigurationsApi';
export * from './releasePipelinesBetaApi';
import { ReleasePipelinesBetaApi } from './releasePipelinesBetaApi';
export * from './releasesBetaApi';
import { ReleasesBetaApi } from './releasesBetaApi';
export * from './scheduledChangesApi';
import { ScheduledChangesApi } from './scheduledChangesApi';
export * from './segmentsApi';
import { SegmentsApi } from './segmentsApi';
export * from './tagsApi';
import { TagsApi } from './tagsApi';
export * from './teamsApi';
import { TeamsApi } from './teamsApi';
export * from './teamsBetaApi';
import { TeamsBetaApi } from './teamsBetaApi';
export * from './userSettingsApi';
import { UserSettingsApi } from './userSettingsApi';
export * from './usersApi';
import { UsersApi } from './usersApi';
export * from './usersBetaApi';
import { UsersBetaApi } from './usersBetaApi';
export * from './webhooksApi';
import { WebhooksApi } from './webhooksApi';
export * from './workflowTemplatesApi';
import { WorkflowTemplatesApi } from './workflowTemplatesApi';
export * from './workflowsApi';
import { WorkflowsApi } from './workflowsApi';
import * as http from 'http';

export class HttpError extends Error {
    constructor (public response: http.IncomingMessage, public body: any, public statusCode?: number) {
        super('HTTP request failed');
        this.name = 'HttpError';
    }
}

export { RequestFile } from '../model/models';

export const APIS = [AIConfigsBetaApi, AccessTokensApi, AccountMembersApi, AccountMembersBetaApi, AccountUsageBetaApi, ApplicationsBetaApi, ApprovalsApi, ApprovalsBetaApi, AuditLogApi, CodeReferencesApi, ContextSettingsApi, ContextsApi, CustomRolesApi, DataExportDestinationsApi, EnvironmentsApi, ExperimentsApi, FeatureFlagsApi, FeatureFlagsBetaApi, FlagImportConfigurationsBetaApi, FlagLinksBetaApi, FlagTriggersApi, FollowFlagsApi, HoldoutsBetaApi, InsightsChartsBetaApi, InsightsDeploymentsBetaApi, InsightsFlagEventsBetaApi, InsightsPullRequestsBetaApi, InsightsRepositoriesBetaApi, InsightsScoresBetaApi, IntegrationAuditLogSubscriptionsApi, IntegrationDeliveryConfigurationsBetaApi, IntegrationsBetaApi, LayersApi, MetricsApi, MetricsBetaApi, OAuth2ClientsApi, OtherApi, PersistentStoreIntegrationsBetaApi, ProjectsApi, RelayProxyConfigurationsApi, ReleasePipelinesBetaApi, ReleasesBetaApi, ScheduledChangesApi, SegmentsApi, TagsApi, TeamsApi, TeamsBetaApi, UserSettingsApi, UsersApi, UsersBetaApi, WebhooksApi, WorkflowTemplatesApi, WorkflowsApi];
