/**
 * NamSor API v2
 * NamSor API v2 : enpoints to process personal names (gender, cultural origin or ethnicity) in all alphabets or languages. By default, enpoints use 1 unit per name (ex. Gender), but Ethnicity classification uses 10 to 20 units per name depending on taxonomy. Use GET methods for small tests, but prefer POST methods for higher throughput (batch processing of up to 100 names at a time). Need something you can\'t find here? We have many more features coming soon. Let us know, we\'ll do our best to add it! 
 *
 * The version of the OpenAPI document: 2.0.29
 * Contact: contact@namsor.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class APIUsageAggregatedOut {
    /**
    * Time unit is DAY, WEEK or MONTH depending on prior usage
    */
    'timeUnit'?: string;
    /**
    * Start datetime of the reporting period
    */
    'periodStart'?: number;
    /**
    * End datetime of the reporting period
    */
    'periodEnd'?: number;
    /**
    * Total usage in the current period
    */
    'totalUsage'?: number;
    /**
    * If the history was truncaded due to data limit
    */
    'historyTruncated'?: boolean;
    /**
    * Data points : usage per DAY, WEEK or MONTH and per apiService
    */
    'data'?: Array<Array<number>>;
    /**
    * apiServices as column headers 
    */
    'colHeaders'?: Array<string>;
    /**
    * dates as row headers 
    */
    'rowHeaders'?: Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "timeUnit",
            "baseName": "timeUnit",
            "type": "string"
        },
        {
            "name": "periodStart",
            "baseName": "periodStart",
            "type": "number"
        },
        {
            "name": "periodEnd",
            "baseName": "periodEnd",
            "type": "number"
        },
        {
            "name": "totalUsage",
            "baseName": "totalUsage",
            "type": "number"
        },
        {
            "name": "historyTruncated",
            "baseName": "historyTruncated",
            "type": "boolean"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "Array<Array<number>>"
        },
        {
            "name": "colHeaders",
            "baseName": "colHeaders",
            "type": "Array<string>"
        },
        {
            "name": "rowHeaders",
            "baseName": "rowHeaders",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return APIUsageAggregatedOut.attributeTypeMap;
    }
}

