generatorName: kotlin
additionalProperties:
  groupId: com.launchdarkly
  packageName: com.launchdarkly.client
  artifactId: launchdarkly-kotlin-client
  hideGenerationTimestamp: true
  oseg.package: oseg.launchdarkly_examples
  oseg.security.ApiKey.api_key: YOUR_API_KEY
  oseg.printApiCallProperty: true
globalProperties:
  apiTests: false
  modelTests: false
  apiDocs: false
  modelDocs: false
