generatorName: java
additionalProperties:
  invokerPackage: com.launchdarkly.client
  apiPackage: com.launchdarkly.client.api
  modelPackage: com.launchdarkly.client.model
  artifactId: launchdarkly-java-client
  hideGenerationTimestamp: true
  oseg.package: oseg.launchdarkly_examples
  oseg.security.ApiKey.api_key: YOUR_API_KEY
  oseg.printApiCallProperty: true
globalProperties:
    apiTests: false
    modelTests: false
    apiDocs: false
    modelDocs: false

