generatorName: php
additionalProperties:
  invokerPackage: "LaunchDarkly\\Client"
  packageName: launchdarkly/client
  composerPackageName: launchdarkly/client
  packageVersion: "1.0.0"
  artifactVersion: "1.0.0"
  oseg.composerPackageName: oseg/launchdarkly_examples
  oseg.namespace: OSEG\LaunchDarklyExamples
  oseg.autoloadLocation: "__DIR__ . '/../vendor/autoload.php'"
  oseg.ignoreOptionalUnset: false
  oseg.security.ApiKey.api_key: YOUR_API_KEY
globalProperties:
    apiTests: false
    modelTests: false
    apiDocs: false
    modelDocs: false
