# coding: utf-8

"""
    NamSor API v2

    NamSor API v2 : enpoints to process personal names (gender, cultural origin or ethnicity) in all alphabets or languages. By default, enpoints use 1 unit per name (ex. Gender), but Ethnicity classification uses 10 to 20 units per name depending on taxonomy. Use GET methods for small tests, but prefer POST methods for higher throughput (batch processing of up to 100 names at a time). Need something you can't find here? We have many more features coming soon. Let us know, we'll do our best to add it! 

    The version of the OpenAPI document: 2.0.29
    Contact: contact@namsor.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from namsor_client.models.community_engage_option_out import CommunityEngageOptionOut
from typing import Optional, Set
from typing_extensions import Self

class APIKeyOut(BaseModel):
    """
    APIKeyOut
    """ # noqa: E501
    api_key: Optional[StrictStr] = Field(default=None, description="The user API Key.", alias="apiKey")
    user_id: Optional[StrictStr] = Field(default=None, description="The user identifier.", alias="userId")
    admin: Optional[StrictBool] = Field(default=None, description="The API Key has admin role.")
    vetted: Optional[StrictBool] = Field(default=None, description="The API Key is vetted (assumed truthful) for machine learning.")
    learnable: Optional[StrictBool] = Field(default=None, description="The API Key is learnable (without assuming truthfulness) for machine learning. Set learnable=false and anonymized=true for highest privacy (ie. to forget data as it's processed).")
    anonymized: Optional[StrictBool] = Field(default=None, description="The API Key is anonymized (using SHA-252 digest for logging). Set learnable=false and anonymized=true for highest privacy (ie. to forget data as it's processed).")
    partner: Optional[StrictBool] = Field(default=None, description="The API Key has partner role.")
    striped: Optional[StrictBool] = Field(default=None, description="The API Key is associated to a valid Stripe account.")
    corporate: Optional[StrictBool] = Field(default=None, description="The API Key has role corporate (ex SWIFT payments instead of Stripe payments).")
    disabled: Optional[StrictBool] = Field(default=None, description="The API Key is temporarily or permanently disabled.")
    explainable: Optional[StrictBool] = Field(default=None, description="The API Key supports the AI explainability option (may require a specific license).")
    ip_address: Optional[StrictStr] = Field(default=None, alias="ipAddress")
    community_engage_option: Optional[CommunityEngageOptionOut] = Field(default=None, alias="communityEngageOption")
    __properties: ClassVar[List[str]] = ["apiKey", "userId", "admin", "vetted", "learnable", "anonymized", "partner", "striped", "corporate", "disabled", "explainable", "ipAddress", "communityEngageOption"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of APIKeyOut from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of community_engage_option
        if self.community_engage_option:
            _dict['communityEngageOption'] = self.community_engage_option.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of APIKeyOut from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "apiKey": obj.get("apiKey"),
            "userId": obj.get("userId"),
            "admin": obj.get("admin"),
            "vetted": obj.get("vetted"),
            "learnable": obj.get("learnable"),
            "anonymized": obj.get("anonymized"),
            "partner": obj.get("partner"),
            "striped": obj.get("striped"),
            "corporate": obj.get("corporate"),
            "disabled": obj.get("disabled"),
            "explainable": obj.get("explainable"),
            "ipAddress": obj.get("ipAddress"),
            "communityEngageOption": CommunityEngageOptionOut.from_dict(obj["communityEngageOption"]) if obj.get("communityEngageOption") is not None else None
        })
        return _obj


