/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.launchdarkly.client.models

import com.launchdarkly.client.models.Message
import com.launchdarkly.client.models.ParentLink

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param key 
 * @param messages 
 * @param model 
 * @param name 
 * @param createdAt 
 * @param version 
 * @param publishedAt 
 * @param links 
 * @param modelConfigKey 
 */


data class AIConfigVariation (

    @Json(name = "key")
    val key: kotlin.String,

    @Json(name = "messages")
    val messages: kotlin.collections.List<Message>,

    @Json(name = "model")
    val model: kotlin.Any,

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "createdAt")
    val createdAt: kotlin.Long,

    @Json(name = "version")
    val version: kotlin.Int,

    @Json(name = "publishedAt")
    val publishedAt: kotlin.Long,

    @Json(name = "_links")
    val links: ParentLink? = null,

    @Json(name = "modelConfigKey")
    val modelConfigKey: kotlin.String? = null

) {


}

