/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.launchdarkly.client.models

import com.launchdarkly.client.models.ApplicationVersionRep
import com.launchdarkly.client.models.Link

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param links The location and content type of related resources
 * @param items A list of the versions for this application
 * @param totalCount The number of versions for this application
 */


data class ApplicationVersionsCollectionRep (

    /* The location and content type of related resources */
    @Json(name = "_links")
    val links: kotlin.collections.Map<kotlin.String, Link>? = null,

    /* A list of the versions for this application */
    @Json(name = "items")
    val items: kotlin.collections.List<ApplicationVersionRep>? = null,

    /* The number of versions for this application */
    @Json(name = "totalCount")
    val totalCount: kotlin.Int? = null

) {


}

