/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.launchdarkly.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param dataWeight The precision weight of the data mean
 * @param priorMean Mean of the prior distribution
 */


data class BayesianNormalStatsRep (

    /* The precision weight of the data mean */
    @Json(name = "dataWeight")
    val dataWeight: java.math.BigDecimal? = null,

    /* Mean of the prior distribution */
    @Json(name = "priorMean")
    val priorMean: java.math.BigDecimal? = null

) {


}

