/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.launchdarkly.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param scheduleKind 
 * @param executionDate 
 * @param waitDuration For workflow stages whose scheduled execution is relative, how far in the future the stage should start.
 * @param waitDurationUnit 
 * @param executeNow Whether the workflow stage should be executed immediately
 * @param description A description of the approval required for this stage
 * @param notifyMemberIds A list of member IDs for the members to request approval from for this stage
 * @param notifyTeamKeys A list of team keys for the teams to request approval from for this stage
 * @param kind 
 */


data class ConditionInput (

    @Json(name = "scheduleKind")
    val scheduleKind: kotlin.String? = null,

    @Json(name = "executionDate")
    val executionDate: kotlin.Long? = null,

    /* For workflow stages whose scheduled execution is relative, how far in the future the stage should start. */
    @Json(name = "waitDuration")
    val waitDuration: kotlin.Int? = null,

    @Json(name = "waitDurationUnit")
    val waitDurationUnit: kotlin.String? = null,

    /* Whether the workflow stage should be executed immediately */
    @Json(name = "executeNow")
    val executeNow: kotlin.Boolean? = null,

    /* A description of the approval required for this stage */
    @Json(name = "description")
    val description: kotlin.String? = null,

    /* A list of member IDs for the members to request approval from for this stage */
    @Json(name = "notifyMemberIds")
    val notifyMemberIds: kotlin.collections.List<kotlin.String>? = null,

    /* A list of team keys for the teams to request approval from for this stage */
    @Json(name = "notifyTeamKeys")
    val notifyTeamKeys: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "kind")
    val kind: kotlin.String? = null

) {


}

