/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.launchdarkly.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param filter A collection of context filters
 * @param sort Specifies a field by which to sort. LaunchDarkly supports sorting by timestamp in ascending order by specifying <code>ts</code> for this value, or descending order by specifying <code>-ts</code>.
 * @param limit Specifies the maximum number of items in the collection to return (max: 50, default: 20)
 * @param continuationToken Limits results to contexts with sort values after the value specified. You can use this for pagination, however, we recommend using the <code>next</code> link instead, because this value is an obfuscated string.
 */


data class ContextSearch (

    /* A collection of context filters */
    @Json(name = "filter")
    val filter: kotlin.String? = null,

    /* Specifies a field by which to sort. LaunchDarkly supports sorting by timestamp in ascending order by specifying <code>ts</code> for this value, or descending order by specifying <code>-ts</code>. */
    @Json(name = "sort")
    val sort: kotlin.String? = null,

    /* Specifies the maximum number of items in the collection to return (max: 50, default: 20) */
    @Json(name = "limit")
    val limit: kotlin.Int? = null,

    /* Limits results to contexts with sort values after the value specified. You can use this for pagination, however, we recommend using the <code>next</code> link instead, because this value is an obfuscated string. */
    @Json(name = "continuationToken")
    val continuationToken: kotlin.String? = null

) {


}

