/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.launchdarkly.client.models

import com.launchdarkly.client.models.ContextAttributeNames

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param items A collection of context attribute name data grouped by kind.
 */


data class ContextAttributeNamesCollection (

    /* A collection of context attribute name data grouped by kind. */
    @Json(name = "items")
    val items: kotlin.collections.List<ContextAttributeNames>

) {


}

