/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.launchdarkly.client.models

import com.launchdarkly.client.models.SourceFlag

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param description A brief description of your changes
 * @param source 
 * @param comment Optional comment describing the approval request
 * @param notifyMemberIds An array of member IDs. These members are notified to review the approval request.
 * @param notifyTeamKeys An array of team keys. The members of these teams are notified to review the approval request.
 * @param includedActions Optional list of the flag changes to copy from the source environment to the target environment. You may include either <code>includedActions</code> or <code>excludedActions</code>, but not both. If neither are included, then all flag changes will be copied.
 * @param excludedActions Optional list of the flag changes NOT to copy from the source environment to the target environment. You may include either <code>includedActions</code> or <code>excludedActions</code>, but not both. If neither are included, then all flag changes will be copied.
 */


data class CreateCopyFlagConfigApprovalRequestRequest (

    /* A brief description of your changes */
    @Json(name = "description")
    val description: kotlin.String,

    @Json(name = "source")
    val source: SourceFlag,

    /* Optional comment describing the approval request */
    @Json(name = "comment")
    val comment: kotlin.String? = null,

    /* An array of member IDs. These members are notified to review the approval request. */
    @Json(name = "notifyMemberIds")
    val notifyMemberIds: kotlin.collections.List<kotlin.String>? = null,

    /* An array of team keys. The members of these teams are notified to review the approval request. */
    @Json(name = "notifyTeamKeys")
    val notifyTeamKeys: kotlin.collections.List<kotlin.String>? = null,

    /* Optional list of the flag changes to copy from the source environment to the target environment. You may include either <code>includedActions</code> or <code>excludedActions</code>, but not both. If neither are included, then all flag changes will be copied. */
    @Json(name = "includedActions")
    val includedActions: kotlin.collections.List<CreateCopyFlagConfigApprovalRequestRequest.IncludedActions>? = null,

    /* Optional list of the flag changes NOT to copy from the source environment to the target environment. You may include either <code>includedActions</code> or <code>excludedActions</code>, but not both. If neither are included, then all flag changes will be copied. */
    @Json(name = "excludedActions")
    val excludedActions: kotlin.collections.List<CreateCopyFlagConfigApprovalRequestRequest.ExcludedActions>? = null

) {

    /**
     * Optional list of the flag changes to copy from the source environment to the target environment. You may include either <code>includedActions</code> or <code>excludedActions</code>, but not both. If neither are included, then all flag changes will be copied.
     *
     * Values: updateOn,updateFallthrough,updateOffVariation,updateRules,updateTargets,updatePrerequisites
     */
    @JsonClass(generateAdapter = false)
    enum class IncludedActions(val value: kotlin.String) {
        @Json(name = "updateOn") updateOn("updateOn"),
        @Json(name = "updateFallthrough") updateFallthrough("updateFallthrough"),
        @Json(name = "updateOffVariation") updateOffVariation("updateOffVariation"),
        @Json(name = "updateRules") updateRules("updateRules"),
        @Json(name = "updateTargets") updateTargets("updateTargets"),
        @Json(name = "updatePrerequisites") updatePrerequisites("updatePrerequisites");
    }
    /**
     * Optional list of the flag changes NOT to copy from the source environment to the target environment. You may include either <code>includedActions</code> or <code>excludedActions</code>, but not both. If neither are included, then all flag changes will be copied.
     *
     * Values: updateOn,updateFallthrough,updateOffVariation,updateRules,updateTargets,updatePrerequisites
     */
    @JsonClass(generateAdapter = false)
    enum class ExcludedActions(val value: kotlin.String) {
        @Json(name = "updateOn") updateOn("updateOn"),
        @Json(name = "updateFallthrough") updateFallthrough("updateFallthrough"),
        @Json(name = "updateOffVariation") updateOffVariation("updateOffVariation"),
        @Json(name = "updateRules") updateRules("updateRules"),
        @Json(name = "updateTargets") updateTargets("updateTargets"),
        @Json(name = "updatePrerequisites") updatePrerequisites("updatePrerequisites");
    }

}

