/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.launchdarkly.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param usingMobileKey Whether to enable availability for mobile SDKs
 * @param usingEnvironmentId Whether to enable availability for client-side SDKs
 */


data class DefaultClientSideAvailability (

    /* Whether to enable availability for mobile SDKs */
    @Json(name = "usingMobileKey")
    val usingMobileKey: kotlin.Boolean,

    /* Whether to enable availability for client-side SDKs */
    @Json(name = "usingEnvironmentId")
    val usingEnvironmentId: kotlin.Boolean

) {


}

