/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.launchdarkly.client.models

import com.launchdarkly.client.models.DeploymentRep
import com.launchdarkly.client.models.Link

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param totalCount The total number of deployments
 * @param items A list of deployments
 * @param links The location and content type of related resources
 */


data class DeploymentCollectionRep (

    /* The total number of deployments */
    @Json(name = "totalCount")
    val totalCount: kotlin.Int,

    /* A list of deployments */
    @Json(name = "items")
    val items: kotlin.collections.List<DeploymentRep>,

    /* The location and content type of related resources */
    @Json(name = "_links")
    val links: kotlin.collections.Map<kotlin.String, Link>? = null

) {


}

