/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.launchdarkly.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param defaultVariation 
 * @param canReshuffle 
 */


data class ExperimentAllocationRep (

    @Json(name = "defaultVariation")
    val defaultVariation: kotlin.Int,

    @Json(name = "canReshuffle")
    val canReshuffle: kotlin.Boolean

) {


}

