/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.launchdarkly.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param startDate 
 * @param stopDate 
 */


data class ExperimentEnabledPeriodRep (

    @Json(name = "startDate")
    val startDate: kotlin.Long? = null,

    @Json(name = "stopDate")
    val stopDate: kotlin.Long? = null

) {


}

