/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.launchdarkly.client.models

import com.launchdarkly.client.models.Experiment
import com.launchdarkly.client.models.Link

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param items An array of experiments
 * @param totalCount The total number of experiments in this project and environment. Does not include legacy experiments.
 * @param links The location and content type of related resources
 */


data class ExperimentCollectionRep (

    /* An array of experiments */
    @Json(name = "items")
    val items: kotlin.collections.List<Experiment>,

    /* The total number of experiments in this project and environment. Does not include legacy experiments. */
    @Json(name = "total_count")
    val totalCount: kotlin.Int? = null,

    /* The location and content type of related resources */
    @Json(name = "_links")
    val links: kotlin.collections.Map<kotlin.String, Link>? = null

) {


}

