/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.launchdarkly.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param instructionIndex The index of the PATCH instruction where the error occurred
 * @param message The error message related to a failed PATCH instruction
 */


data class ExpiringTargetError (

    /* The index of the PATCH instruction where the error occurred */
    @Json(name = "instructionIndex")
    val instructionIndex: kotlin.Int,

    /* The error message related to a failed PATCH instruction */
    @Json(name = "message")
    val message: kotlin.String

) {


}

