/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.launchdarkly.client.models

import com.launchdarkly.client.models.FeatureFlagScheduledChange
import com.launchdarkly.client.models.Link

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param items Array of scheduled changes
 * @param links The location and content type of related resources
 */


data class FeatureFlagScheduledChanges (

    /* Array of scheduled changes */
    @Json(name = "items")
    val items: kotlin.collections.List<FeatureFlagScheduledChange>,

    /* The location and content type of related resources */
    @Json(name = "_links")
    val links: kotlin.collections.Map<kotlin.String, Link>? = null

) {


}

