/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.launchdarkly.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param filename The imported file name, including the extension
 * @param status The imported file status
 */


data class FileRep (

    /* The imported file name, including the extension */
    @Json(name = "filename")
    val filename: kotlin.String? = null,

    /* The imported file status */
    @Json(name = "status")
    val status: kotlin.String? = null

) {


}

