/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.launchdarkly.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param ruleId The ID of the variation or rollout of the flag to use. Use \"fallthrough\" for the default targeting behavior when the flag is on.
 * @param flagConfigVersion The flag version
 * @param notInExperimentVariationId The ID of the variation to route traffic not part of the experiment analysis to. Defaults to variation ID of baseline treatment, if set.
 */


data class FlagInput (

    /* The ID of the variation or rollout of the flag to use. Use \"fallthrough\" for the default targeting behavior when the flag is on. */
    @Json(name = "ruleId")
    val ruleId: kotlin.String,

    /* The flag version */
    @Json(name = "flagConfigVersion")
    val flagConfigVersion: kotlin.Int,

    /* The ID of the variation to route traffic not part of the experiment analysis to. Defaults to variation ID of baseline treatment, if set. */
    @Json(name = "notInExperimentVariationId")
    val notInExperimentVariationId: kotlin.String? = null

) {


}

