/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.launchdarkly.client.models

import com.launchdarkly.client.models.FlagImportIntegration
import com.launchdarkly.client.models.FlagImportIntegrationCollectionLinks

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param links 
 * @param items An array of flag import configurations
 */


data class FlagImportIntegrationCollection (

    @Json(name = "_links")
    val links: FlagImportIntegrationCollectionLinks,

    /* An array of flag import configurations */
    @Json(name = "items")
    val items: kotlin.collections.List<FlagImportIntegration>

) {


}

