/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.launchdarkly.client.models

import com.launchdarkly.client.models.Link

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param name Status of the flag
 * @param links 
 * @param lastRequested Timestamp of last time flag was requested
 * @param default Default value seen from code
 */


data class FlagStatusRep (

    /* Status of the flag */
    @Json(name = "name")
    val name: FlagStatusRep.Name,

    @Json(name = "_links")
    val links: kotlin.collections.Map<kotlin.String, Link>,

    /* Timestamp of last time flag was requested */
    @Json(name = "lastRequested")
    val lastRequested: java.time.OffsetDateTime? = null,

    /* Default value seen from code */
    @Json(name = "default")
    val default: kotlin.Any? = null

) {

    /**
     * Status of the flag
     *
     * Values: new,inactive,active,launched
     */
    @JsonClass(generateAdapter = false)
    enum class Name(val value: kotlin.String) {
        @Json(name = "new") new("new"),
        @Json(name = "inactive") inactive("inactive"),
        @Json(name = "active") active("active"),
        @Json(name = "launched") launched("launched");
    }

}

