/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.launchdarkly.client.models

import com.launchdarkly.client.models.VariationSummary

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param variations 
 * @param prerequisites The number of prerequisites for this flag
 */


data class FlagSummary (

    @Json(name = "variations")
    val variations: kotlin.collections.Map<kotlin.String, VariationSummary>,

    /* The number of prerequisites for this flag */
    @Json(name = "prerequisites")
    val prerequisites: kotlin.Int

) {


}

