/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.launchdarkly.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param name Name of the bound
 * @param `value` Value of the bound
 */


data class InsightsChartBounds (

    /* Name of the bound */
    @Json(name = "name")
    val name: kotlin.String,

    /* Value of the bound */
    @Json(name = "value")
    val `value`: kotlin.Long

) {


}

