/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.launchdarkly.client.models

import com.launchdarkly.client.models.InsightGroup
import com.launchdarkly.client.models.InsightGroupCollectionMetadata
import com.launchdarkly.client.models.InsightGroupCollectionScoreMetadata
import com.launchdarkly.client.models.Link

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param totalCount The total number of insight groups
 * @param items A list of insight groups
 * @param links The location and content type of related resources
 * @param metadata 
 * @param scoreMetadata 
 */


data class InsightGroupCollection (

    /* The total number of insight groups */
    @Json(name = "totalCount")
    val totalCount: kotlin.Int,

    /* A list of insight groups */
    @Json(name = "items")
    val items: kotlin.collections.List<InsightGroup>,

    /* The location and content type of related resources */
    @Json(name = "_links")
    val links: kotlin.collections.Map<kotlin.String, Link>? = null,

    @Json(name = "metadata")
    val metadata: InsightGroupCollectionMetadata? = null,

    @Json(name = "scoreMetadata")
    val scoreMetadata: InsightGroupCollectionScoreMetadata? = null

) {


}

