/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.launchdarkly.client.models

import com.launchdarkly.client.models.CapabilityConfigPost

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param name The name of the integration configuration
 * @param configValues The unique set of fields required to configure the integration. Refer to the <code>formVariables</code> field in the corresponding <code>manifest.json</code> at https://github.com/launchdarkly/integration-framework/tree/main/integrations for a full list of fields for the integration you wish to configure.
 * @param enabled Whether the integration configuration is enabled. If omitted, defaults to true
 * @param tags Tags for the integration
 * @param capabilityConfig 
 */


data class IntegrationConfigurationPost (

    /* The name of the integration configuration */
    @Json(name = "name")
    val name: kotlin.String,

    /* The unique set of fields required to configure the integration. Refer to the <code>formVariables</code> field in the corresponding <code>manifest.json</code> at https://github.com/launchdarkly/integration-framework/tree/main/integrations for a full list of fields for the integration you wish to configure. */
    @Json(name = "configValues")
    val configValues: kotlin.collections.Map<kotlin.String, kotlin.Any>,

    /* Whether the integration configuration is enabled. If omitted, defaults to true */
    @Json(name = "enabled")
    val enabled: kotlin.Boolean? = null,

    /* Tags for the integration */
    @Json(name = "tags")
    val tags: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "capabilityConfig")
    val capabilityConfig: CapabilityConfigPost? = null

) {


}

