/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.launchdarkly.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param config 
 * @param on Whether the integration configuration is active. Default value is false.
 * @param tags Tags to associate with the integration
 * @param name Name to identify the integration
 */


data class IntegrationDeliveryConfigurationPost (

    @Json(name = "config")
    val config: kotlin.collections.Map<kotlin.String, kotlin.Any>,

    /* Whether the integration configuration is active. Default value is false. */
    @Json(name = "on")
    val on: kotlin.Boolean? = null,

    /* Tags to associate with the integration */
    @Json(name = "tags")
    val tags: kotlin.collections.List<kotlin.String>? = null,

    /* Name to identify the integration */
    @Json(name = "name")
    val name: kotlin.String? = null

) {


}

