/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.launchdarkly.client.models

import com.launchdarkly.client.models.ExperimentBayesianResultsRep
import com.launchdarkly.client.models.MetricInGroupRep

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param metric 
 * @param results 
 */


data class MetricInGroupResultsRep (

    @Json(name = "metric")
    val metric: MetricInGroupRep,

    @Json(name = "results")
    val results: ExperimentBayesianResultsRep

) {


}

