/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.launchdarkly.client.models

import com.launchdarkly.client.models.DeploymentCollectionRep
import com.launchdarkly.client.models.FlagReferenceCollectionRep
import com.launchdarkly.client.models.PullRequestLeadTimeRep

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id The pull request internal ID
 * @param externalId The pull request number
 * @param title The pull request title
 * @param status The pull request status
 * @param author The pull request author
 * @param createTime 
 * @param baseCommitKey The pull request base commit key
 * @param headCommitKey The pull request head commit key
 * @param filesChanged The number of files changed
 * @param linesAdded The number of lines added
 * @param linesDeleted The number of lines deleted
 * @param url The pull request URL
 * @param mergeTime 
 * @param mergeCommitKey The pull request merge commit key
 * @param deployments 
 * @param flagReferences 
 * @param leadTime 
 */


data class PullRequestRep (

    /* The pull request internal ID */
    @Json(name = "id")
    val id: java.util.UUID,

    /* The pull request number */
    @Json(name = "externalId")
    val externalId: kotlin.String,

    /* The pull request title */
    @Json(name = "title")
    val title: kotlin.String,

    /* The pull request status */
    @Json(name = "status")
    val status: kotlin.String,

    /* The pull request author */
    @Json(name = "author")
    val author: kotlin.String,

    @Json(name = "createTime")
    val createTime: kotlin.Long,

    /* The pull request base commit key */
    @Json(name = "baseCommitKey")
    val baseCommitKey: kotlin.String,

    /* The pull request head commit key */
    @Json(name = "headCommitKey")
    val headCommitKey: kotlin.String,

    /* The number of files changed */
    @Json(name = "filesChanged")
    val filesChanged: kotlin.Int,

    /* The number of lines added */
    @Json(name = "linesAdded")
    val linesAdded: kotlin.Int,

    /* The number of lines deleted */
    @Json(name = "linesDeleted")
    val linesDeleted: kotlin.Int,

    /* The pull request URL */
    @Json(name = "url")
    val url: kotlin.String,

    @Json(name = "mergeTime")
    val mergeTime: kotlin.Long? = null,

    /* The pull request merge commit key */
    @Json(name = "mergeCommitKey")
    val mergeCommitKey: kotlin.String? = null,

    @Json(name = "deployments")
    val deployments: DeploymentCollectionRep? = null,

    @Json(name = "flagReferences")
    val flagReferences: FlagReferenceCollectionRep? = null,

    @Json(name = "leadTime")
    val leadTime: PullRequestLeadTimeRep? = null

) {


}

