/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.launchdarkly.client.models

import com.launchdarkly.client.models.Link
import com.launchdarkly.client.models.RepositoryRep

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param links 
 * @param items An array of repositories
 */


data class RepositoryCollectionRep (

    @Json(name = "_links")
    val links: kotlin.collections.Map<kotlin.String, Link>,

    /* An array of repositories */
    @Json(name = "items")
    val items: kotlin.collections.List<RepositoryRep>

) {


}

