/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.launchdarkly.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param sdk The SDK name, or \"Unknown\"
 * @param version The version number, or \"Unknown\"
 */


data class SdkVersionRep (

    /* The SDK name, or \"Unknown\" */
    @Json(name = "sdk")
    val sdk: kotlin.String,

    /* The version number, or \"Unknown\" */
    @Json(name = "version")
    val version: kotlin.String

) {


}

