/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.launchdarkly.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param time The timestamp
 * @param `value` The value for the given timestamp
 */


data class Series (

    /* The timestamp */
    @Json(name = "time")
    val time: kotlin.Long,

    /* The value for the given timestamp */
    @Json(name = "value")
    val `value`: java.math.BigDecimal

) {


}

