/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.launchdarkly.client.models

import com.launchdarkly.client.models.ActionInput
import com.launchdarkly.client.models.ConditionInput

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param name The stage name
 * @param executeConditionsInSequence Whether to execute the conditions in sequence for the given stage
 * @param conditions An array of conditions for the stage
 * @param action 
 */


data class StageInput (

    /* The stage name */
    @Json(name = "name")
    val name: kotlin.String? = null,

    /* Whether to execute the conditions in sequence for the given stage */
    @Json(name = "executeConditionsInSequence")
    val executeConditionsInSequence: kotlin.Boolean? = null,

    /* An array of conditions for the stage */
    @Json(name = "conditions")
    val conditions: kotlin.collections.List<ConditionInput>? = null,

    @Json(name = "action")
    val action: ActionInput? = null

) {


}

