/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.launchdarkly.client.models

import com.launchdarkly.client.models.Link
import com.launchdarkly.client.models.Team

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param items An array of teams
 * @param links The location and content type of related resources
 * @param totalCount The number of teams
 */


data class Teams (

    /* An array of teams */
    @Json(name = "items")
    val items: kotlin.collections.List<Team>,

    /* The location and content type of related resources */
    @Json(name = "_links")
    val links: kotlin.collections.Map<kotlin.String, Link>? = null,

    /* The number of teams */
    @Json(name = "totalCount")
    val totalCount: kotlin.Int? = null

) {


}

