/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.launchdarkly.client.models

import com.launchdarkly.client.models.Link

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param links 
 * @param id 
 * @param name The name of the token
 * @param ending The last few characters of the token
 * @param serviceToken Whether this is a service token
 */


data class TokenSummary (

    @Json(name = "_links")
    val links: kotlin.collections.Map<kotlin.String, Link>? = null,

    @Json(name = "_id")
    val id: kotlin.String? = null,

    /* The name of the token */
    @Json(name = "name")
    val name: kotlin.String? = null,

    /* The last few characters of the token */
    @Json(name = "ending")
    val ending: kotlin.String? = null,

    /* Whether this is a service token */
    @Json(name = "serviceToken")
    val serviceToken: kotlin.Boolean? = null

) {


}

