/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.launchdarkly.client.models

import com.launchdarkly.client.models.ParameterRep

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param name The treatment name. This is the variation name from the flag.
 * @param allocationPercent The percentage of traffic allocated to this treatment during the iteration
 * @param id The treatment ID. This is the variation ID from the flag.
 * @param baseline Whether this treatment is the baseline to compare other treatments against
 * @param parameters Details on the flag and variation used for this treatment
 */


data class TreatmentRep (

    /* The treatment name. This is the variation name from the flag. */
    @Json(name = "name")
    val name: kotlin.String,

    /* The percentage of traffic allocated to this treatment during the iteration */
    @Json(name = "allocationPercent")
    val allocationPercent: kotlin.String,

    /* The treatment ID. This is the variation ID from the flag. */
    @Json(name = "_id")
    val id: kotlin.String? = null,

    /* Whether this treatment is the baseline to compare other treatments against */
    @Json(name = "baseline")
    val baseline: kotlin.Boolean? = null,

    /* Details on the flag and variation used for this treatment */
    @Json(name = "parameters")
    val parameters: kotlin.collections.List<ParameterRep>? = null

) {


}

