generatorName: typescript-axios
additionalProperties:
  npmName: chatwoot_client
  oseg.npmName: "@oseg/chatwoot"
  oseg.security.userApiKey.api_key: USER_API_KEY
  oseg.security.agentBotApiKey.api_key: AGENT_BOT_API_KEY
  oseg.security.platformAppApiKey.api_key: PLATFORM_APP_API_KEY
  oseg.printApiCallProperty: true
globalProperties:
  apiTests: false
  modelTests: false
  apiDocs: false
  modelDocs: false
